name: Prod Release to Github Pages (Backup)

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'decooio/crust-files'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20 
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: Run install
        run: yarn install

      - name: Build
        run: yarn export
      
      - name: Deploy 🚀
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.DECOO_PAT }}
          SRC_FOLDER: out
          DEST_OWNER: decooio
          DEST_REPO: crust-files-deploy
          DEST_BRANCH: main
          DEST_FOLDER: docs
